version: "3"
services:
  pkgsite:
    build:
      dockerfile: "pkgsite.Dockerfile"
      context: "."
    command: "/pkgsite -direct_proxy -proxy_url https://artifactory.gcp.anz/artifactory/api/go/go"
    ports:
      - "8080:8080"
