name: deploy profiles
on:
  push:
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Version
        id: version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/*/}
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup - gcloud / gsutil
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.ACTIONS_SERVICE_ACC }}
          export_default_credentials: true
      - name: Set default project
        run: |
          gcloud config set core/project joshcarp
          gcloud auth configure-docker
          gcloud config set run/region us-central1
      - name: Build
        run: docker build . -t gcr.io/joshcarp/pkgsite:${{steps.version.outputs.VERSION}}
      - name: Deploy
        run: docker push gcr.io/joshcarp/pkgsite:${{steps.version.outputs.VERSION}}
